server:
  port: 9900
logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.zuul: 'OFF'
endpoints:
  health:
    sensitive: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5

ribbon:
  ServerListRefreshInterval: 5000

zuul:
  routes:
    stores:
      path: /stores/**
      strip-prefix: false
    customers:
      path: /customers/**
      strip-prefix: false